[package]
org = "chama"
name = "student_reg_backend"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "student_reg_backend.store"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"

